### ISSUE TITLE
Nuget: Unable to find ServiceStack.

### ISSUE THREAD

**Issue by mikekidder** [ServiceStackApps/typescript-redux#3]
First things first.  This is one awesome tutorial!   Very nice to see a Typescript/React/Redux tutorial so well laid out.

Just noticed the VS project has the packages at 4.0.53, but Nuget still a version behind at 4.0.52

I however was able to jump right into the TypeScriptRedux directory and use it with Visual Studio Code.   I used Puer (npm package, supports live reloading) to quickly launch in browser and start playing.  Impressive!!!

**Comment by mythz** [comment]
Hi Mike, thanks for the feedback!

Yeah this tutorial is still fresh so it's using the [v4.0.53 Pre-Release Packages on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet), we're actually planning on releasing v4.0.54 tomorrow after which we'll update the project to reference the NuGet packages instead.

Only the last Networked Shape Creator (Example 9) depends on a server back-end, the others are pure client-side-only examples so you should be able to run them from their individual folders.

I'll update this issue once I've changed this project to point to the v4.0.54 NuGet packages.

**Comment by mythz** [comment]
This has now been updated to the latest v4.0.54 version of ServiceStack that was just released in this commit: https://github.com/ServiceStackApps/typescript-redux/commit/2fd1f5c38ca9f6a9c8aef1201560b9af2435a8a0
