### ISSUE TITLE
Added ```width``` and ```height``` defaults and ```'COUNTER_CHANGE'``` action

### ISSUE THREAD

**Issue by cramhead** [ServiceStackApps/typescript-redux#5]
Thanks so much for making this. It's really helping to pull things together for me. 

An area where things broke down for me was [Example 7](https://github.com/ServiceStackApps/typescript-redux/blob/master/src/TypeScriptRedux/src/example07/Counter.tsx). The initial state in the create store was undefined so when setting the state `state[action.field]` was `NAN`. Also, the `COUNTER_CHANGE` action is missing at that point. 
I set the initial state to be  `{counter: 0, width: 0, height: 0}` and pulled the `COUNTER_CHANGE` action from lower in the document

**Comment by mythz** [comment]
Hmmm, haven't been able to repro the issue yet. 

What are the steps to see the error after `/example07/` is loaded in a browser?

Also are you able to repro the JS error from:
http://servicestackapps.github.io/typescript-redux/example07/

**Comment by cramhead** [comment]
Oh, sorry. I get buttons and labels showing, but when I pressed on the buttons nothing happened. I only found the solution by console.logging the state and action properties to the screen

**Comment by mythz** [comment]
Weird that I don't see the error, which browser are you using?

**Comment by cramhead** [comment]
Well, just in looking that the document I would have expected it to fail, because there was not default state for width and height, only counter is there at that point. I'm using Google Chrome    48.0.2564.116 (Official Build) (64-bit)

**Comment by mythz** [comment]
Sorry for the back-and-forth but I want to be able to repro the issue before I resolve it - and I haven't been yet able to. I'm also using the latest Chrome (OSX+Win) and I've tried loading example 07:

http://servicestackapps.github.io/typescript-redux/example07/

And have tried pressing every button after reloading the page one at a time (in both Chrome Win + OSX) and haven't been able to see any JavaScript error.

Can you list the exact steps after loading:

http://servicestackapps.github.io/typescript-redux/example07/

Which button are you pressing to get the error? If you can send me a screenshot of the error that would help to.

**Comment by cramhead** [comment]
Oh, sorry. I wasn't clear enough. I was typing the code as defined in the readme.md. It didn't the reader to modify the their initial state and reducer. The link to the example works correctly. I had clicked the link to example07 thinking that it would have been helpful at locating the problem. I think I just made it more complex. Sorry about the confusion. 
So in effort to be more clear: in the `README.md` file if you search for `{Type}_{Event}` that scenario ends up failing when I modify the Counter so that it dispatches `COUNTER_CHANGE` actions.
I guess at that point in the `README.md` you really start picking up the pace, so may be I should I have expected to start thinking more independently.
Thanks again for putting this together. I'm sure it's not a small task.

**Comment by mythz** [comment]
ok no worries sounds like the issue is that you haven't got to the [updated app.tsx](https://github.com/ServiceStackApps/typescript-redux#apptsx-3) yet. 

The examples are only meant to be runnable at the end of each example just before demo time.
