### ISSUE TITLE
No need for reduxify

### ISSUE THREAD

**Issue by buzinas** [ServiceStackApps/typescript-redux#6]
React-redux connect can be used as a decorator, e.g:

``` javascript
@connect(
  (state) => ({ name: state.name }),
  (dispatch) => ({})
)
export class TextField extends React.Component<any, any> {
  render() {
    const { name } = this.props;
    return <div>Hello, {name}!</div>;
  }
}
```

There is no need to create another wrapper.

**Comment by mythz** [comment]
Wow that's awesome! This makes it a lot more appealing to use, saves a bunch of code and removes an unnecessary artifact/delegation. 

Example updated to remove `@reduxify()` and replace with Redux `@connect()` in this commit: https://github.com/ServiceStackApps/typescript-redux/commit/0760efc43236e1a0812ddabb2eb113b200c34015

Thanks for the heads up :+1:

**Comment by buzinas** [comment]
Great :)

Btw, very nice examples, they helped me a lot!
