### ISSUE TITLE
Broken on IE/Edge

### ISSUE THREAD

**Issue by riesvriend** [ServiceStackApps/typescript-redux#7]
I've been looking around for tutorials on React and Typescript, and this is just great. Thanks for creating it. 

Working through the exercises I found that they only work in Chrome. IE11 or Edge render a blank page from here: http://redux.servicestack.net/

Working through the tutorial, I ran into IE11 "Object.assign is undefined". Something seems off with the ES6 shim, maybe that's a clue but so far I could not fix it.

**Comment by mythz** [comment]
Not sure what's up with Edge, it's not rendering but it's not showing any JS errors on load just an unknown System.js error after a long delay. 

It works in every other browser I have, inc. Chrome, Firefox, Safari, Opera, Brave, Vivaldi, etc. So I expect it to be another IE issue which I don't have time to hunt down, but I'll leave this issue open in-case someone else wants to have a crack at it.

**Comment by Layoric** [comment]
Seems to be related to minification and IE 11.

https://github.com/systemjs/systemjs/issues/517#issuecomment-139872916

When using JSPM, there are additional files in `jspm_packages` directory, including `system-polyfills.src.js` might should help fix this issue. Looks `system-polyfills.src.js` has to be included before any `System.` calls are made, so probably best to leave it out of minification if your build process doesn't enforce the order it's included.

**Comment by riesvriend** [comment]
@Layoric I could make it work based on your suggestions.

In index.html, if I load the e6-shim before system.js, it all works OK in both IE11 and Edge. 
On another note, both IE and Edge browsers have a 2 second loading delay that I don't see in Chrome. The F12 profiler suggest it's all loading up instantly but that's not how it displays. Anyways, it works!

``` html
<script src="https://cdnjs.cloudflare.com/ajax/libs/es6-shim/0.35.0/es6-shim.js"></script>
<script src="/jspm_packages/system.js"></script>
```

**Comment by riesvriend** [comment]
Similar to IE workaround used by MS during typescript demo. 
https://github.com/Microsoft/typescript-build2016-demos/blob/master/ng-reddit/index.html#L13

**Comment by riesvriend** [comment]
Fixed it! 

See fork with branch at https://github.com/riesvriend/typescript-redux-iefix/tree/IE-object-assign-fix

Two problems:
- ES6 Object.assign was not properly imported in the typescript files. Loading the es6 shim as per my previous comment was not fixing the root cause.
- Edge/IE need a shim for EventSource to work. I included one in the project now.

The readme still needs some updating. I will leave it at this, please feel free to merge this into the master.

**Comment by mythz** [comment]
ok thanks, can you [send a pull request](https://help.github.com/articles/creating-a-pull-request/) so we can merge this?

**Comment by riesvriend** [comment]
Done

On Fri, Apr 15, 2016 at 12:12 AM, Demis Bellot notifications@github.com
wrote:

> ok thanks, can you send a pull request
> https://help.github.com/articles/creating-a-pull-request/ so we can
> merge this?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/ServiceStackApps/typescript-redux/issues/7#issuecomment-210177072

## 

ries@amsterdamsoftware.com
Ries Vriend

Amsterdam Software
Nachtwachtlaan 20
1058 EA  Amsterdam
The Netherlands
Office +31 20 620 56 97
Mobile +31 6 517 55 208
www.amsterdamsoftware.com

**Comment by riesvriend** [comment]
I think the best way to close this issue, is to include both required shims before system.js loads. Leave them out of the deps bundle. Use es6-shim for Object.apply() and event-source-polyfill for EventSource. 

Works for me.  Its a very minor startup perf cost and it keeps it al simple. 

`<script src="https://cdnjs.cloudflare.com/ajax/libs/es6-shim/0.35.0/es6-shim.js"></script>`
`<script src="/jspm_packages/npm/event-source-polyfill@0.0.7/eventsource.js"></script>`

**Comment by mythz** [comment]
@riesvriend I've decided to leave [a note at the end of the guide](https://github.com/ServiceStackApps/typescript-redux#fixes-for-internet-explorer-and-microsoft-edge) to points users to checkout your repo for fixes with IE/MS Edge. In 2016 there really should be no need for ES6 or SSE shims so hopefully MS will get their act together and fix it.
